#!/usr/bin/env python3
"""
Jarvis Dashboard interactive setup.

Collects credentials and feature preferences, then writes `.env` at the
project root (which is symlinked into `backend/.env`). Safe to re-run:
existing values become the defaults on the next pass.

Stdlib-only — no pip install step required before this runs.
"""

from __future__ import annotations

import os
import re
import secrets
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = REPO_ROOT / ".env"
ENV_EXAMPLE = REPO_ROOT / ".env.example"

ALL_FEATURES = [
    ("discover", "Discover (movie/series recommendations) — required", True),
    ("media", "Jellyfin media library browser"),
    ("torrents", "Torrent client (qBittorrent / Transmission)"),
    ("docker", "Docker container management"),
    ("system", "System monitoring (CPU/RAM/disk/bandwidth)"),
    ("files", "File explorer"),
    ("tasks", "Task list"),
]


def color(s: str, code: str) -> str:
    if not sys.stdout.isatty():
        return s
    return f"\033[{code}m{s}\033[0m"


def banner(msg: str) -> None:
    print()
    print(color("━" * 64, "90"))
    print(color(f"  {msg}", "1;36"))
    print(color("━" * 64, "90"))


def info(msg: str) -> None:
    print(color(f"  {msg}", "90"))


def ask(prompt: str, default: str = "", secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    try:
        if secret and default:
            val = input(f"{prompt}{suffix} (press enter to keep existing): ").strip()
        else:
            val = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        val = ""
    return val or default


def ask_bool(prompt: str, default: bool) -> bool:
    d = "Y/n" if default else "y/N"
    try:
        val = input(f"{prompt} [{d}]: ").strip().lower()
    except EOFError:
        val = ""
    if not val:
        return default
    return val.startswith("y")


def ask_choice(prompt: str, choices: list[str], default: str) -> str:
    assert default in choices
    rendered = "/".join(c.upper() if c == default else c for c in choices)
    while True:
        try:
            val = input(f"{prompt} [{rendered}]: ").strip().lower()
        except EOFError:
            val = ""
        if not val:
            return default
        if val in choices:
            return val
        print(color(f"  please pick one of: {', '.join(choices)}", "33"))


def parse_env(path: Path) -> dict[str, str]:
    """Minimal .env parser — handles KEY=VALUE, ignores comments/blank lines."""
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2)
        # Strip surrounding quotes if present
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            val = val[1:-1]
        out[key] = val
    return out


def write_env(path: Path, values: dict[str, str]) -> None:
    """Write env atomically. Preserves key order loosely via the template."""
    template_keys: list[str] = []
    if ENV_EXAMPLE.exists():
        for line in ENV_EXAMPLE.read_text().splitlines():
            m = re.match(r"^#?\s*([A-Z_][A-Z0-9_]*)\s*=", line)
            if m and m.group(1) not in template_keys:
                template_keys.append(m.group(1))
    # Add any keys we're writing that weren't in the template
    for k in values:
        if k not in template_keys:
            template_keys.append(k)

    lines = ["# Generated by scripts/setup.py — safe to edit by hand.", ""]
    for key in template_keys:
        if key in values:
            val = values[key]
            # Quote if value contains whitespace or #
            if re.search(r"[\s#]", val):
                val = '"' + val.replace('"', '\\"') + '"'
            lines.append(f"{key}={val}")
    content = "\n".join(lines) + "\n"

    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content)
    os.replace(tmp, path)


def run_setup() -> dict[str, str]:
    existing = parse_env(ENV_PATH)
    result: dict[str, str] = dict(existing)  # start from current, overwrite as we go

    banner("Jarvis Dashboard — setup")
    if existing:
        info(f"Found existing .env with {len(existing)} values.")
        choice = ask_choice(
            "Reuse existing, Reconfigure, or Cancel?",
            ["reuse", "reconfigure", "cancel"],
            "reuse",
        )
        if choice == "cancel":
            print(color("  cancelled — no changes written.", "33"))
            sys.exit(0)
        if choice == "reuse":
            info(".env left untouched.")
            return result
    else:
        info("No .env found — starting fresh.")

    # ── Feature selection ───────────────────────────────────────────────
    banner("1. Pick features")
    info("Discover (movies) is always enabled. Toggle the rest to taste.")
    enabled: set[str] = {"discover"}
    current_feats_raw = (existing.get("ENABLED_FEATURES") or "all").lower()
    currently_on = (
        {f[0] for f in ALL_FEATURES}
        if current_feats_raw in ("", "all", "*")
        else {p.strip() for p in current_feats_raw.split(",") if p.strip()}
    )
    for entry in ALL_FEATURES:
        key, label = entry[0], entry[1]
        forced = len(entry) > 2 and entry[2]
        if forced:
            print(color(f"  [x] {label}", "32"))
            enabled.add(key)
            continue
        if ask_bool(f"  Enable {label}?", default=(key in currently_on)):
            enabled.add(key)
    result["ENABLED_FEATURES"] = ",".join(sorted(enabled))

    # ── TMDB (required for Discover) ────────────────────────────────────
    banner("2. TMDB API key (required for Discover)")
    info("Free key: https://www.themoviedb.org/settings/api")
    result["TMDB_API_KEY"] = ask("TMDB_API_KEY", default=existing.get("TMDB_API_KEY", ""), secret=True)

    # ── Jellyfin (only if media enabled, but Discover uses it too for library-check) ──
    banner("3. Jellyfin")
    info("Used by the Media tab and the 'Play on Jellyfin' button on Discover.")
    want_jellyfin = "media" in enabled or ask_bool(
        "  Configure Jellyfin for 'Play on Jellyfin' from Discover?",
        default=bool(existing.get("JELLYFIN_API_KEY")),
    )
    if want_jellyfin:
        result["JELLYFIN_BASE"] = ask(
            "JELLYFIN_BASE",
            default=existing.get("JELLYFIN_BASE", "http://localhost:8096"),
        )
        result["JELLYFIN_API_KEY"] = ask(
            "JELLYFIN_API_KEY",
            default=existing.get("JELLYFIN_API_KEY", ""),
            secret=True,
        )
    else:
        result["JELLYFIN_API_KEY"] = existing.get("JELLYFIN_API_KEY", "")

    # ── Torrents ────────────────────────────────────────────────────────
    if "torrents" in enabled:
        banner("4. Torrent client")
        client = ask_choice(
            "  Which client?",
            ["qbittorrent", "transmission", "none"],
            existing.get("TORRENT_CLIENT") or "qbittorrent",
        )
        if client == "none":
            enabled.discard("torrents")
            result["ENABLED_FEATURES"] = ",".join(sorted(enabled))
        else:
            result["TORRENT_CLIENT"] = client
            if client == "qbittorrent":
                result["QBIT_BASE"] = ask(
                    "QBIT_BASE",
                    default=existing.get("QBIT_BASE", "http://localhost:8080/api/v2"),
                )
                result["QBIT_USER"] = ask("QBIT_USER", default=existing.get("QBIT_USER", ""))
                result["QBIT_PASS"] = ask("QBIT_PASS", default=existing.get("QBIT_PASS", ""), secret=True)
            else:
                result["TRANSMISSION_BASE"] = ask(
                    "TRANSMISSION_BASE",
                    default=existing.get("TRANSMISSION_BASE", "http://localhost:9091/transmission/rpc"),
                )
                result["TRANSMISSION_USER"] = ask("TRANSMISSION_USER", default=existing.get("TRANSMISSION_USER", ""))
                result["TRANSMISSION_PASS"] = ask(
                    "TRANSMISSION_PASS",
                    default=existing.get("TRANSMISSION_PASS", ""),
                    secret=True,
                )

    # ── Media / file roots ──────────────────────────────────────────────
    banner("5. Folders")
    home_default = existing.get("FILE_HOME") or str(Path.home())
    if "files" in enabled:
        info("FILE_HOME is where the File Explorer starts browsing (default: your home).")
        result["FILE_HOME"] = ask("FILE_HOME", default=home_default)
    result["MEDIA_PATH"] = ask(
        "MEDIA_PATH (root of your media library)",
        default=existing.get("MEDIA_PATH", "/data/media"),
    )

    # ── Optional extras ─────────────────────────────────────────────────
    banner("6. Optional extras")
    result["WEATHER_CITY"] = ask(
        "WEATHER_CITY (leave blank to disable weather)",
        default=existing.get("WEATHER_CITY", ""),
    )

    existing_api_key = existing.get("API_KEY", "")
    if existing_api_key:
        info("API_KEY already set — leaving as-is.")
        result["API_KEY"] = existing_api_key
    else:
        if ask_bool(
            "  Generate an API_KEY to protect non-localhost backend access?",
            default=False,
        ):
            result["API_KEY"] = secrets.token_urlsafe(32)
            info(f"Generated API_KEY: {result['API_KEY']}")

    return result


def main() -> int:
    if not ENV_EXAMPLE.exists():
        print(color("  warning: .env.example not found — template order may be off", "33"))

    values = run_setup()

    if ENV_PATH.exists():
        backup = ENV_PATH.with_name(".env.bak")
        shutil.copy2(ENV_PATH, backup)
        info(f"Backed up previous .env → {backup.name}")

    write_env(ENV_PATH, values)
    print()
    print(color(f"  .env written to {ENV_PATH}", "32"))

    # Ensure backend symlink exists
    backend_env = REPO_ROOT / "backend" / ".env"
    if not backend_env.exists() and not backend_env.is_symlink():
        try:
            backend_env.symlink_to(ENV_PATH)
            info(f"  created symlink {backend_env} → .env")
        except OSError as e:
            info(f"  could not symlink backend/.env ({e}); pydantic-settings may not find it")

    print()
    print(color("  Setup complete. Launch with:", "1;32"))
    print("    ./setup.sh run         # native (venv + npm)")
    print("    ./setup.sh run docker  # via docker compose")
    print()
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print()
        print(color("  interrupted — .env not modified", "33"))
        sys.exit(130)
